# Integration tests work by installing dayz server
# using steamcmd. Dayz server requires an authented
# steam account to download the server files. This
# means the account cannot have steam gaurd, otherwise
# steamcmd will block, asking for a steam gaurd code.
# It is recomended to use a throw away account for this.

name: Integration Tests
on:
  pull_request:
  push:
    branches:
      - main

env:
  DAYZ_APP_ID: 223350

jobs:
  integration:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        server:
        - kamyshowdown
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Pre-requisites
      run: |
        sudo apt-get update -qq > /dev/null
        sudo apt-get install lib32gcc-s1 -y -qq

    - name: Setup steamcmd
      uses: CyberAndrii/setup-steamcmd@v1

    - run: mkdir -p ~/servers/dayz-server/

    - name: Update app
      run: |
        steamcmd \
          +force_install_dir ~/servers/dayz-server/ \
          +login ${{ secrets.STEAM_USERNAME }} ${{ secrets.STEAM_PASSWORD}} \
          +app_update ${{ env.DAYZ_APP_ID }} \
          +quit
