# Integration tests work by installing dayz server
# using steamcmd. Dayz server requires an authented
# steam account to download the server files. This
# means the account cannot have steam gaurd, otherwise
# steamcmd will block, asking for a steam gaurd code.
# It is recomended to use a throw away account for this.

name: Integration Tests
on:
  pull_request:
  push:
    branches:
      - main

env:
  DAYZ_APP_ID: 223350

jobs:
  integration:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        server:
        - kamyshowdown
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Pre-requisites
      run: |
        sudo apt-get update -qq > /dev/null
        sudo apt-get install lib32gcc-s1 -y -qq

    - name: Setup steamcmd
      uses: CyberAndrii/setup-steamcmd@v1

    - run: mkdir -p /opt/dayz-server

    - name: Update app
      run: |
        steamcmd \
          +force_install_dir /opt/dayz-server/ \
          +login ${{ secrets.STEAM_USERNAME }} ${{ secrets.STEAM_PASSWORD}} \
          +app_update ${{ env.DAYZ_APP_ID }} \
          +quit

    - name: Add dayz user and group
      run: |
        sudo adduser \
          --system \
          --no-create-home \
          --disabled-login \
          --group dayz

    - name: Deploy systemd service
      run: |
        cat > dayz-server.service <<EOF
        [Unit]
        Description=DayZ Dedicated Server
        Wants=network-online.target
        After=network-online.target
        
        [Service]
        ExecStart=/opt/dayz-server/DayZServer -config=serverDZ.cfg -port=23>
        WorkingDirectory=/opt/dayz-server
        LimitNOFILE=100000
        User=dayz
        Group=dayz
        Restart=on-failure
        RestartSec=30s
        
        [Install]
        WantedBy=multi-user.target
        EOF

        sudo cp dayz-server.service /etc/systemd/system/dayz-server.service
        sudo systemctl daemon-reload
        sudo systemctl disable dayz-server

    # - name: Deploy cfgplayerspawnpoints.xml
    #   run: |
    #     cp servers/${{ matrix.server }}/cfgplayerspawnpoints.xml \
    #     servers/dayz-server/mpmissions/dayzOffline.chernarusplus/cfgplayerspawnpoints.xml

    - run: sudo systemctl start dayz-server
    - run: sleep 10
    - run: sudo systemctl status dayz-server
