name: Lint
on:
  pull_request:
    paths:
      - "**.xml"
  push:
    paths:
      - "**.xml"
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate XML
      uses: anyone-developer/anyone-validate-xml@main
      with:
        file-extension: '.xml'
